apiVersion: v2
name: twampy
description: A Helm chart for Kubernetes to deploy twampy. Twampy is a TWAMP client and server implementation written in Python. Orginally developed by Nokia and customized by https://github.com/darox/python3-twampy.
type: application
version: 0.0.2
appVersion: "0.0.2"
icon: https://raw.githubusercontent.com/darox/python3-twampy/main/assets/icon.png


